AdminLTE.MVC/ViewModels/ReaderViewModel.cs
using Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace AdminLTE.ViewModels
{
    public class ReaderViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        public string Sname { get; set; }

        [Display(Name = "Отчество")]
        public string Pname { get; set; }

        public int ClassId { get; set; }

        public string ClassName { get; set; }

        public string UniqueId { get; set; }

        public static implicit operator ReaderViewModel(Reader r)
        {
            if (r == null)
            {
                return new ReaderViewModel();
            }

            return new ReaderViewModel
            {
                Id = r.Id,
                Name = r.Name,
                Pname = r.Pname,
                Sname = r.Sname,
                ClassId = r.ClassId,
                UniqueId = r.UniqueId,
                ClassName = r.Class.Name
            };
        }
    }
}

AdminLTE.MVC/Controllers/ReaderController.cs
using System.Collections.Generic;
using System.Linq;
using AdminLTE.ViewModels;
using Data.Entities;
using Data.Repos;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE.Controllers
{
    public class ReaderController : Controller
    {
        public IActionResult Index()
        {
            return View(GetAllReaders());
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Classes = ReposExtensions.GetEntities<Class>().Select(x => (ClassViewModel)x).ToList();

            var reader = (ReaderViewModel)ReposExtensions.GetEntity<Reader>(x => x.Id == id);
            return PartialView("_Edit", reader);
        }

        [HttpPost]
        public IActionResult Edit(ReaderViewModel model)
        {
            Reader reader;
            if (model.Id > 0)
            {
                reader = ReposExtensions.GetEntity<Reader>(x => x.Id == model.Id);
            }
            else
            {
                reader = new Reader();
            }

            string inn = model.UniqueId == null ? null : model.UniqueId.Trim();
            var hasUnique = ReposExtensions.GetEntity<Reader>(x => x.UniqueId == inn);
            if (hasUnique != null && hasUnique.Id != reader.Id && inn != null)
            {
                ViewBag.ErrorMessage = "Читатель с таким ИНН уже есть в базе";
                return PartialView("_ReaderContent", GetAllReaders());
            }

            reader.ClassId = model.ClassId;
            reader.Name = model.Name.Trim();
            reader.Sname = model.Sname;
            reader.Pname = model.Pname;
            reader.UniqueId = inn;

            var saveResult = ReposExtensions.AddOrUpdate(reader);
            if (saveResult == false)
            {
                ViewBag.ErrorMessage = "Ошибка при сохранении!";
            }

            return PartialView("_ReaderContent", GetAllReaders());
        }

        [HttpPost]
        public IActionResult Search(string filter_text)
        {
            var allreaders = GetAllReaders();
            if (string.IsNullOrWhiteSpace(filter_text))
            {
                return PartialView("_ReaderContent", allreaders);
            }

            filter_text = filter_text.Trim();

            var isInn = filter_text.All(char.IsDigit);
            if (isInn)
            {
                allreaders = allreaders.Where(x => x.UniqueId == filter_text).ToArray();
                return PartialView("_ReaderContent", allreaders);
            }

            var arr = filter_text.Split(new string[] { " ", "\t" }, System.StringSplitOptions.RemoveEmptyEntries);
            if (arr.Length == 1)
            {
                allreaders = allreaders.Where(x =>
                        x.Name.ToLower().Contains(arr[0].ToLower())
                        || (x.Pname != null && x.Pname.ToLower().Contains(arr[0].ToLower()))
                        || (x.Sname != null && x.Sname.ToLower().Contains(arr[0].ToLower())))
                    .ToArray();
                return PartialView("_ReaderContent", allreaders);
            }
            else if (arr.Length == 2)
            {
                allreaders = allreaders.Where(x =>
                        x.Sname.ToLower().Contains(arr[0].ToLower())
                        && x.Name.ToLower().Contains(arr[1].ToLower()))
                    .ToArray();
                return PartialView("_ReaderContent", allreaders);
            }
            else if (arr.Length == 3)
            {
                allreaders = allreaders.Where(x =>
                        x.Sname.ToLower().Contains(arr[0].ToLower())
                        && x.Name.ToLower().Contains(arr[1].ToLower())
                        && x.Pname.ToLower().Contains(arr[2].ToLower()))
                    .ToArray();
                return PartialView("_ReaderContent", allreaders);
            }
            else
            {
                return PartialView("_ReaderContent", allreaders);
            }
        }

        private IEnumerable<ReaderViewModel> GetAllReaders()
        {
            var retVal = ReposExtensions.GetEntities<Reader>()
                .Select(x => (ReaderViewModel)x).OrderBy(x => x.Sname).ToArray();
            return retVal;
        }
    }
}

AdminLTE.MVC/Views/Reader/Index.cshtml
@model IEnumerable<AdminLTE.ViewModels.ReaderViewModel>
@{ ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; }

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/site.js" type="text/javascript"></script>

<head>
    <script type="text/javascript">
    $(function () {
            $.ajaxSetup({ cache: false });
            $(".readerItemAdd").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>

    <script type="text/javascript">
        function SearchReaders(element) {
            if (event.keyCode == 13) {
                var text = element.value;
                var data = {
                    filter_text: text
                };

                $.ajax({
                    type: 'POST',
                    url: '/Reader/Search',
                    data: data,

                    success: function (result) {
                        $('#divReaderContent').html(result);
                        return true;
                    },

                    failure: function (response) {
                        alert("failure" + response.responseText);
                    },

                    error: function (response) {
                        alert("error" + response.responseText);
                    }
                });
            }
        }
    </script>
</head>

<body>

    <div class="form-group-lg">

        <button type="button" style="border: none; background-color: transparent;">@Html.ActionLink("Новый читатель", "Edit", "Reader", new { id = 0 }, new { @class = "readerItemAdd btn btn-sm btn-primary" })</button>

        <input type="text" id="txt_search_by_fio_or_inn" placeholder="Поиск"
               style="margin-left: 3%; width: 15%;" onkeyup="SearchReaders(this); return false;" />
    </div>

    <div id="divReaderContent">
        @await Html.PartialAsync("_ReaderContent", Model)
    </div>

</body>

AdminLTE.MVC/Views/Reader/_Edit.cshtml
@model AdminLTE.ViewModels.ReaderViewModel
@using AdminLTE.ViewModels
@{
    Layout = null;
}


<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<body>

    <div class="modal-content" id="modalContentEdit" role="dialog">
        <div class="modal-header">

            @if (Model != null && Model.Id == 0)
            {
                <h6>Добавление нового читателя</h6>
            }

            @if (Model != null && Model.Id > 0)
            {
                <h6>Редактирование читателя</h6>
            }

            <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">

                @if (Model != null)
                {
                    <div class="form-group">
                        <input class="form-control" placeholder="HasChanged" id="HasChanged"
                               type="hidden" />
                    </div>

                    <div class="form-group">
                        <input class="form-control" placeholder="Id" asp-for="Id" value="@Model.Id"
                               hidden="hidden" id="txtReaderId" />
                        <span asp-validation-for="Id"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="UniqueId" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Inn" asp-for="UniqueId"
                               autocomplete="off" id="txtInn" onchange="OnchangeValue()"
                               value="@Model.UniqueId" />
                        <span asp-validation-for="UniqueId"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Sname" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Фамилия" asp-for="Sname"
                               autocomplete="off" id="txtSname" onchange="OnchangeValue()"
                               value="@Model.Sname" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Sname"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Имя" asp-for="Name"
                               autocomplete="off" id="txtName" onchange="OnchangeValue()"
                               value="@Model.Name" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Name"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Pname" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Отчество" asp-for="Pname"
                               autocomplete="off" id="txtPname" onchange="OnchangeValue()"
                               value="@Model.Pname" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Pname"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ClassId" class="font-for-label">Выберите класс:</label><br />
                        <select style="width: 30%;" asp-for="ClassId" id="selectedClass" onchange="OnchangeValue()">
                            @if (ViewBag != null && ViewBag.Classes != null)
                            {
                                <option value=""></option>
                                var itemsArr = ViewBag.Classes as List<ClassViewModel>;
                                foreach (var grItem in itemsArr)
                                {
                                    <option value="@grItem.Id">@grItem.Name</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="ClassId"></span>
                    </div>

                    <div class="form-group" style="text-align: right;">
                        <input type="submit" value="Сохранить" id="editOrdBtnOk" onclick="SaveReader()"
                               class="btn btn-success" data-dismiss="modal" area-hidden="true"
                               style="background-color: lightgreen; width: 100px;" />
                    </div>
                }
                else
                {
                    <h3>Читатель не найден</h3>
                }

            </dl>
        </div>
    </div>

</body>

AdminLTE.MVC/Views/Reader/_ReaderContent.cshtml
@model IEnumerable<AdminLTE.ViewModels.ReaderViewModel>
@{ Layout = null; }


<head>
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".readerItemAdd").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
</head>

@if (ViewBag.ErrorMessage != null)
{
    <div>
        <p style="color: red;">@ViewBag.ErrorMessage</p>
    </div>
}

<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info" id="authors-grid">
            <thead>
                <tr role="row">
                    <th width="10%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        UniqueId
                    </th>

                    <th width="20%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Фамилия
                    </th>

                    <th width="20%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Имя
                    </th>

                    <th width="20%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Отчество
                    </th>

                    <th width="10%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Класс
                    </th>

                    <th tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Редактировать
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    var classes = Model.ToList();
                    foreach (var cl in classes)
                    {
                        <tr role="row" class="odd">
                            <td align="center">@cl.UniqueId</td>
                            <td align="center">@cl.Sname</td>
                            <td align="center">@cl.Name</td>
                            <td align="center">@cl.Pname</td>
                            <td align="center">@cl.ClassName</td>

                            <td align="center">
                                @Html.ActionLink("Редактировать", "Edit", "Reader", new { id = cl.Id }, new { @class = "readerItemAdd" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>