AdminLTE.MVC/ViewModels/BookshelfViewModel.cs
using Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace AdminLTE.ViewModels
{
    public class BookshelfViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Наименование")]
        public string Name { get; set; }

        public static implicit operator BookshelfViewModel(BookShelf b)
        {
            if (b == null)
            {
                return new BookshelfViewModel();
            }

            return new BookshelfViewModel
            {
                Id = b.Id,
                Name = b.Name
            };
        }
    }
}

AdminLTE.MVC/Controllers/BookshelfController.cs
using System.Collections.Generic;
using System.Linq;
using AdminLTE.ViewModels;
using Data.Entities;
using Data.Repos;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE.Controllers
{
    public class BookshelfController : Controller
    {
        public IActionResult Index()
        {
            return View(GetAllBookshelfs());
        }

        public IActionResult Edit(int id)
        {
            var bookShelf = (BookshelfViewModel)ReposExtensions.GetEntity<BookShelf>(x => x.Id == id);
            return PartialView("_Edit", bookShelf);
        }

        [HttpPost]
        public IActionResult Edit(BookshelfViewModel model)
        {
            BookShelf bookShelf;
            if (model.Id > 0)
            {
                bookShelf = ReposExtensions.GetEntity<BookShelf>(x => x.Id == model.Id);
            }
            else
            {
                bookShelf = new BookShelf();
            }

            bookShelf.Name = model.Name.Trim();
            var saveResult = ReposExtensions.AddOrUpdate(bookShelf);
            if (saveResult == false)
            {
                ViewBag.ErrorMessage = "Ошибка при сохранении!";
            }

            return PartialView("_BookshelContent", GetAllBookshelfs());
        }

        private IEnumerable<BookshelfViewModel> GetAllBookshelfs()
        {
            var retVal = ReposExtensions.GetEntities<BookShelf>()
                .Select(x => (BookshelfViewModel)x).OrderBy(x => x.Name).ToArray();
            return retVal;
        }
    }
}

AdminLTE.MVC/Views/Bookshelf/Index.cshtml
@model IEnumerable<AdminLTE.ViewModels.BookshelfViewModel>
@{ ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; }

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/site.js" type="text/javascript"></script>

<head>
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".bookshelfItemAdd").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
</head>

<body>

    <div class="form-group-lg">

        <button type="button" style="border: none; background-color: transparent;">@Html.ActionLink("Новый стиллаж", "Edit", "Bookshelf", new { id = 0 }, new { @class = "bookshelfItemAdd btn btn-sm btn-primary" })</button>

    </div>

    <div id="divBookshelfContent">
        @await Html.PartialAsync("_BookshelContent", Model)
    </div>

</body>

AdminLTE.MVC/Views/Bookshelf/_BookshelContent.cshtml
@model IEnumerable<AdminLTE.ViewModels.BookshelfViewModel>
@{ Layout = null; }


<head>
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".bookshelfItemEdit").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
</head>

<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info" id="authors-grid">
            <thead>
                <tr role="row">
                    <th width="60%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Стиллаж
                    </th>
                    <th tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Редактировать
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    var bookshelfs = Model.ToList();
                    foreach (var bookshelf in bookshelfs)
                    {
                        <tr role="row" class="odd">
                            <td align="center">@bookshelf.Name</td>
                            <td align="center">
                                @Html.ActionLink("Редактировать", "Edit", "Bookshelf", new { id = bookshelf.Id }, new { @class = "bookshelfItemEdit" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

AdminLTE.MVC/Views/Bookshelf/_Edit.cshtml
@model AdminLTE.ViewModels.BookshelfViewModel
@{
    Layout = null;
}


<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<body>

    <div class="modal-content" id="modalContentEdit" role="dialog">
        <div class="modal-header">

            @if (Model != null && Model.Id == 0)
            {
                <h6>Добавление новой полки</h6>
            }

            @if (Model != null && Model.Id > 0)
            {
                <h6>Редактирование полки</h6>
            }

            <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">

                @if (Model != null)
                {
                    <div class="form-group">
                        <input class="form-control" placeholder="HasChanged" id="HasChanged"
                               type="hidden" />
                    </div>

                    <div class="form-group">
                        <input class="form-control" placeholder="Id" asp-for="Id" value="@Model.Id"
                               hidden="hidden" id="txtBookshelfId" />
                        <span asp-validation-for="Id"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Название полки" asp-for="Name"
                               autocomplete="off" id="txtName"
                               value="@Model.Name" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Name"></span>
                    </div>

                    <div class="form-group" style="text-align: right;">
                        <input type="submit" value="Сохранить" id="editOrdBtnOk" onclick="SaveBookshelf()"
                               class="btn btn-success" data-dismiss="modal" area-hidden="true"
                               style="background-color: lightgreen; width: 100px;" />
                    </div>
                }
                else
                {
                    <h3>Полка не найдена</h3>
                }

            </dl>
        </div>
    </div>

</body>