AdminLTE.MVC/ViewModels/ClassViewModel.cs
using Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace AdminLTE.ViewModels
{
    public class ClassViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Наименование")]
        public string Name { get; set; }

        public static implicit operator ClassViewModel(Class c)
        {
            if (c == null)
            {
                return new ClassViewModel();
            }

            return new ClassViewModel
            {
                Id = c.Id,
                Name = c.Name
            };
        }
    }
}

AdminLTE.MVC/Controllers/ClassController.cs
using System.Collections.Generic;
using System.Linq;
using AdminLTE.ViewModels;
using Data.Entities;
using Data.Repos;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE.Controllers
{
    public class ClassController : Controller
    {
        public IActionResult Index()
        {
            return View(GetAllClasses());
        }

        public IActionResult Edit(int id)
        {
            var cl = (ClassViewModel)ReposExtensions.GetEntity<Class>(x => x.Id == id);
            return PartialView("_Edit", cl);
        }

        [HttpPost]
        public IActionResult Edit(ClassViewModel model)
        {
            Class cl;
            if (model.Id > 0)
            {
                cl = ReposExtensions.GetEntity<Class>(x => x.Id == model.Id);
            }
            else
            {
                cl = new Class();
            }

            cl.Name = model.Name.Trim();
            var saveResult = ReposExtensions.AddOrUpdate(cl);
            if (saveResult == false)
            {
                ViewBag.ErrorMessage = "Ошибка при сохранении!";
            }

            return PartialView("_ClassContent", GetAllClasses());
        }

        private IEnumerable<ClassViewModel> GetAllClasses()
        {
            var retVal = ReposExtensions.GetEntities<Class>()
                .Select(x => (ClassViewModel)x).OrderBy(x => x.Name).ToArray();
            return retVal;
        }
    }
}

AdminLTE.MVC/Views/Class/Index.cshtml
@model IEnumerable<AdminLTE.ViewModels.ClassViewModel>
@{ ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; }

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/site.js" type="text/javascript"></script>

<head>
    <script type="text/javascript">$(function () {
            $.ajaxSetup({ cache: false });
            $(".classItemAdd").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })</script>
</head>

<body>

    <div class="form-group-lg">

        <button type="button" style="border: none; background-color: transparent;">@Html.ActionLink("Новый класс", "Edit", "Class", new { id = 0 }, new { @class = "classItemAdd btn btn-sm btn-primary" })</button>

    </div>

    <div id="divClassContent">
        @await Html.PartialAsync("_ClassContent", Model)
    </div>

</body>

AdminLTE.MVC/Views/Class/_ClassContent.cshtml
@model IEnumerable<AdminLTE.ViewModels.ClassViewModel>
@{ Layout = null; }


<head>
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".classItemEdit").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
</head>

<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info" id="authors-grid">
            <thead>
                <tr role="row">
                    <th width="20%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Наименование
                    </th>
                    
                    <th tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                        Редактировать
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    var classes = Model.ToList();
                    foreach (var cl in classes)
                    {
                        <tr role="row" class="odd">
                            <td align="center">@cl.Name</td>
                            
                            <td align="center">
                                @Html.ActionLink("Редактировать", "Edit", "Class", new { id = cl.Id }, new { @class = "classItemEdit" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

AdminLTE.MVC/Views/Class/_Edit.cshtml
@model AdminLTE.ViewModels.ClassViewModel
@using AdminLTE.ViewModels
@{
    Layout = null;
}


<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<body>

    <div class="modal-content" id="modalContentEdit" role="dialog">
        <div class="modal-header">

            @if (Model != null && Model.Id == 0)
            {
                <h6>Добавление нового класса</h6>
            }

            @if (Model != null && Model.Id > 0)
            {
                <h6>Редактирование класса</h6>
            }

            <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">

                @if (Model != null)
                {
                    <div class="form-group">
                        <input class="form-control" placeholder="HasChanged" id="HasChanged"
                               type="hidden" />
                    </div>

                    <div class="form-group">
                        <input class="form-control" placeholder="Id" asp-for="Id" value="@Model.Id"
                               hidden="hidden" id="txtClassId" />
                        <span asp-validation-for="Id"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Класс" asp-for="Name"
                               autocomplete="off" id="txtClassName"
                               value="@Model.Name" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Name"></span>
                    </div>

                    <div class="form-group" style="text-align: right;">
                        <input type="submit" value="Сохранить" id="editOrdBtnOk" onclick="SaveClass()"
                               class="btn btn-success" data-dismiss="modal" area-hidden="true"
                               style="background-color: lightgreen; width: 100px;" />
                    </div>
                }
                else
                {
                    <h3>Класс не найден</h3>
                }

            </dl>
        </div>
    </div>

</body>