AdminLTE.MVC/ViewModels/GroupViewModel.cs
using Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace AdminLTE.ViewModels
{
    public class GroupViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Наименование")]
        public string Name { get; set; }

        public static implicit operator GroupViewModel(BookGroup g)
        {
            if (g == null)
            {
                return new GroupViewModel();
            }

            return new GroupViewModel
            {
                Id = g.Id,
                Name = g.Name
            };
        }
    }
}

AdminLTE.MVC/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Linq;
using AdminLTE.ViewModels;
using Data.Entities;
using Data.Repos;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE.Controllers
{
    public class GroupController : Controller
    {
        public IActionResult Index()
        {
            return View(GetAllGroups());
        }

        public IActionResult Edit(int id)
        {
            var group = (GroupViewModel)ReposExtensions.GetEntity<BookGroup>(x => x.Id == id);
            return PartialView("_Edit", group);
        }

        [HttpPost]
        public IActionResult Edit(GroupViewModel model)
        {
            BookGroup group;
            if (model.Id > 0)
            {
                group = ReposExtensions.GetEntity<BookGroup>(x => x.Id == model.Id);
            }
            else
            {
                group = new BookGroup();
            }

            group.Name = model.Name.Trim();
            var saveResult = ReposExtensions.AddOrUpdate(group);
            if (saveResult == false)
            {
                ViewBag.ErrorMessage = "Ошибка при сохранении!";
            }

            return PartialView("_GroupsContent", GetAllGroups());
        }

        private IEnumerable<GroupViewModel> GetAllGroups()
        {
            var retVal = ReposExtensions.GetEntities<BookGroup>()
                .Select(x => (GroupViewModel)x).OrderBy(x => x.Name).ToArray();
            return retVal;
        }
    }
}

AdminLTE.MVC/Views/Group/Index.cshtml
@model IEnumerable<AdminLTE.ViewModels.GroupViewModel>
@{ ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml"; }

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/site.js" type="text/javascript"></script>

<head>
    <script type="text/javascript">$(function () {
            $.ajaxSetup({ cache: false });
            $(".groupItemAdd").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })</script>
</head>

<div class="form-group-lg">
    <button type="button" style="border: none; background-color: transparent;">@Html.ActionLink("Новая группа", "Edit", "Group", new { id = 0 }, new { @class = "groupItemAdd btn btn-sm btn-primary" })</button>
</div>

<div id="divGroupsContent">
    @await Html.PartialAsync("_GroupsContent", Model)
</div>

AdminLTE.MVC/Views/Group/_Edit.cshtml
@model AdminLTE.ViewModels.GroupViewModel
@{
    Layout = null;
}


<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<body>

    <div class="modal-content" id="modalContentEdit" role="dialog">
        <div class="modal-header">

            @if (Model != null && Model.Id == 0)
            {
                <h6>Добавление новой группы</h6>
            }

            @if (Model != null && Model.Id > 0)
            {
                <h6>Редактирование группы</h6>
            }

            <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">

                @if (Model != null)
                {
                    <div class="form-group">
                        <input class="form-control" placeholder="HasChanged" id="HasChanged"
                               type="hidden" />
                    </div>

                    <div class="form-group">
                        <input class="form-control" placeholder="Id" asp-for="Id" value="@Model.Id"
                               hidden="hidden" id="txtGroupId" />
                        <span asp-validation-for="Id"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="font-for-label"></label><br />
                        <input class="form-control" placeholder="Имя автора" asp-for="Name"
                               autocomplete="off" id="txtName"
                               value="@Model.Name" onchange="UpperFirstChar(this); return false;" />
                        <span asp-validation-for="Name"></span>
                    </div>

                    <div class="form-group" style="text-align: right;">
                        <input type="submit" value="Сохранить" id="editOrdBtnOk" onclick="SaveGroup()"
                               class="btn btn-success" data-dismiss="modal" area-hidden="true"
                               style="background-color: lightgreen; width: 100px;" />
                    </div>
                }
                else
                {
                    <h3>Автор не найден</h3>
                }

            </dl>
        </div>
    </div>

</body>

AdminLTE.MVC/Views/Group/_GroupsContent.cshtml
@model IEnumerable<AdminLTE.ViewModels.GroupViewModel>
@{ Layout = null; }

    <head>
        <script type="text/javascript">
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".groupItemEdit").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
        </script>
    </head>



    <div class="row">
        <div class="col-sm-12">
            <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info" id="authors-grid">
                <thead>
                    <tr role="row">
                        <th width="60%" tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                            Группа
                        </th>
                        <th tabindex="0" aria-controls="authors-grid" rowspan="1" style="text-align: center;">
                            Редактировать
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        var groups = Model.ToList();
                        foreach (var group in groups)
                        {
                            <tr role="row" class="odd">
                                <td align="center">@group.Name</td>
                                <td align="center">
                                    @Html.ActionLink("Редактировать", "Edit", "Group", new { id = group.Id }, new { @class = "groupItemEdit" })
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>


    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>